# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    config.vm.box = "debian/stretch64"

    # we don't use synced folders so disable the default to not require rsync binary on Windows
    config.vm.synced_folder ".", "/net"

    config.vm.post_up_message = '
VM started! Run "vagrant ssh <vmname>" to connect.
The VM defined here is connected with two virtual links with VirtIO NICs on each side.
Use lspci to find the bus addresses of the VirtIO NICs, it will probably be 0000:00:08.0 and 0000:00:09.0.
Our NIC driver is installed in /net, run with sudo, e.g.
    sudo /net/app/fwd 0000:00:08.0
'
    config.vm.define :nw_stack do |config|
        # IPs are required but not actually used by us.
        config.vm.network "private_network", ip: "10.100.1.10", nic_type: "virtio", virtualbox__intnet: "net1",
            libvirt__network_name: "net1", :libvirt__dhcp_enabled => false
        config.vm.network "private_network", ip: "10.100.2.10", nic_type: "virtio", virtualbox__intnet: "net2",
            libvirt__network_name: "net2", :libvirt__dhcp_enabled => false 
        config.vm.provider "virtualbox" do |vb|
            vb.memory = '1536'
            vb.cpus = '4'
            vb.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
            vb.customize ["modifyvm", :id, "--nicpromisc3", "allow-all"]
        end

        config.vm.provision "shell", privileged: true, inline: %Q{
            sed -i s/deb.debian.org/archive.debian.org/g /etc/apt/sources.list
            apt-get update
            apt-get install -y cmake build-essential pciutils vim
            cd /net/
            sudo -u vagrant cmake .
            sudo -u vagrant make
        }


        config.vm.provision "shell", privileged: true, run: "always", inline: <<-SHELL
            /net/setup_hugepage.sh
        SHELL
    end
end

# Check if a VM was already created before
def created?(vm_name, provider='virtualbox')
    File.exist?(".vagrant/machines/#{vm_name}/#{provider}/id")
end

